# Generated by Django 5.0.10 on 2026-06-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chuyên mục')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Mô tả')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=170, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Chuyên mục blog',
                'verbose_name_plural': 'Chuyên mục blog',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, default='', help_text='2-3 câu hiển thị trên card và meta description nếu trống.', max_length=300, verbose_name='Tóm tắt')),
                ('content_md', models.TextField(help_text='Hỗ trợ Markdown chuẩn — heading, list, code, link, image, blockquote.', verbose_name='Nội dung (Markdown)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('cover_alt', models.CharField(blank=True, default='', help_text='Mô tả ảnh cho SEO + screen reader.', max_length=200, verbose_name='Alt ảnh')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=170, verbose_name='Meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='blog/og/', verbose_name='OG image')),
                ('canonical_url', models.URLField(blank=True, default='', verbose_name='Canonical URL')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Xuất bản lúc')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5, help_text='Hiển thị trên card. Cập nhật tay hoặc tính từ word count.', verbose_name='Thời gian đọc (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory', verbose_name='Chuyên mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'), models.Index(fields=['category', 'status', '-published_at'], name='blog_blogpo_categor_5a3f62_idx'), models.Index(fields=['is_featured', '-published_at'], name='blog_blogpo_is_feat_1c3903_idx')],
            },
        ),
    ]
