# Generated by Django 5.0.10 on 2026-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('view_sensitive', 'Xem dữ liệu nhạy cảm'), ('login', 'Đăng nhập'), ('login_failed', 'Đăng nhập thất bại'), ('permission_change', 'Đổi quyền')], max_length=30, verbose_name='Hành động')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='ID đối tượng')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Thay đổi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Trung tâm Đào tạo Lái xe', help_text='Tên đầy đủ, hiển thị trên header, footer, email, hóa đơn.', max_length=200, verbose_name='Tên trung tâm')),
                ('brand_short_name', models.CharField(default='ĐA', help_text='2-3 ký tự, dùng cho logo text khi chưa có ảnh logo. VD: ĐA, ABC.', max_length=20, verbose_name='Tên viết tắt')),
                ('slogan', models.CharField(blank=True, default='Học lái xe an toàn, đúng lộ trình.', max_length=255, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, help_text='2-3 câu mô tả trung tâm, dùng cho meta description mặc định.', verbose_name='Mô tả ngắn')),
                ('logo', models.ImageField(blank=True, help_text='PNG/SVG, transparent bg, kích thước tối thiểu 512x512.', null=True, upload_to='brand/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='ICO/PNG 32x32 hoặc 64x64.', null=True, upload_to='brand/', verbose_name='Favicon')),
                ('og_image', models.ImageField(blank=True, help_text='1200x630, dùng cho Open Graph khi share Facebook/Zalo.', null=True, upload_to='brand/', verbose_name='Ảnh chia sẻ mạng xã hội')),
                ('hotline', models.CharField(default='0900000000', help_text='Định dạng máy: 0903456789 (không dấu chấm, không khoảng trắng).', max_length=20, verbose_name='Hotline')),
                ('hotline_display', models.CharField(default='0900.000.000', help_text='Định dạng đẹp cho UI: 0903.456.789', max_length=30, verbose_name='Hotline hiển thị')),
                ('email', models.EmailField(default='info@example.vn', max_length=254, verbose_name='Email')),
                ('address_line', models.CharField(default='Đồng Xoài, Bình Phước', max_length=255, verbose_name='Địa chỉ')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(blank=True, default='Bình Phước', max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kinh độ')),
                ('map_embed_url', models.URLField(blank=True, help_text='Vào Google Maps → Share → Embed a map → copy src của iframe vào đây.', max_length=500, verbose_name='Google Map embed URL')),
                ('working_hours_text', models.CharField(default='T2 đến T7: 7:30 đến 18:00. Chủ nhật: 8:00 đến 12:00', max_length=255, verbose_name='Giờ làm việc')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('zalo_oa_id', models.CharField(blank=True, max_length=100, verbose_name='Zalo OA ID')),
                ('zalo_url', models.URLField(blank=True, verbose_name='Zalo OA URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('license_info', models.CharField(blank=True, default='Giấy phép số ABC/SGTVT do Sở GTVT cấp', max_length=255, verbose_name='Giấy phép')),
                ('company_full_name', models.CharField(blank=True, help_text='Tên ghi trên hóa đơn, hợp đồng. Có thể khác Tên trung tâm.', max_length=255, verbose_name='Tên đầy đủ pháp nhân')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('meta_title_default', models.CharField(blank=True, max_length=70, verbose_name='Tiêu đề SEO mặc định')),
                ('meta_description_default', models.CharField(blank=True, max_length=170, verbose_name='Mô tả SEO mặc định')),
                ('stat_students_count', models.PositiveIntegerField(default=10000, help_text='Hiển thị ở trust strip. Cập nhật định kỳ thủ công.', verbose_name='Số học viên đã đỗ (hiển thị)')),
                ('stat_pass_rate_percent', models.PositiveSmallIntegerField(default=89, verbose_name='Tỉ lệ đỗ lần đầu (%)')),
                ('stat_years_experience', models.PositiveSmallIntegerField(default=12, verbose_name='Số năm kinh nghiệm')),
                ('stat_practice_area_m2', models.PositiveIntegerField(default=8000, verbose_name='Sân tập (m²)')),
            ],
            options={
                'verbose_name': 'Thông tin trung tâm',
                'verbose_name_plural': 'Thông tin trung tâm',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Khóa')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Giá trị')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'ordering': ['key'],
            },
        ),
    ]
