# Generated by Django 5.0.10 on 2026-06-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', help_text='Viết hoa không dấu, đúng tên trên CMND chủ tài khoản.', max_length=200, verbose_name='Tên chủ TK'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', help_text='TK liên kết với Casso để nhận chuyển khoản đặt cọc.', max_length=30, verbose_name='Số tài khoản nhận'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_code',
            field=models.CharField(blank=True, default='BIDV', help_text='Mã chuẩn NAPAS: BIDV, VCB, TCB, VPB, MB, ACB... Xem napas.com.vn.', max_length=20, verbose_name='Mã ngân hàng (VietQR)'),
        ),
    ]
