# Generated by Django 5.0.10 on 2026-06-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Tạo'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('view_sensitive', 'Xem dữ liệu nhạy cảm'), ('login', 'Đăng nhập'), ('login_failed', 'Đăng nhập thất bại'), ('logout', 'Đăng xuất'), ('permission_change', 'Đổi quyền')], max_length=30, verbose_name='Hành động'),
        ),
    ]
