# Generated by Django 5.0.10 on 2026-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integrationcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationcredential',
            name='provider',
            field=models.CharField(choices=[('casso', 'Casso (đối soát QR)'), ('fb', 'Facebook Lead Ads'), ('zns', 'Zalo ZNS (deprecated)'), ('smtp', 'Email SMTP (deprecated)')], max_length=20, verbose_name='Tích hợp'),
        ),
    ]
