# Generated by Django 5.0.10 on 2026-06-10 11:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_delete_courseschedule'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Định dạng ORD-XXXXXX. Dùng làm nội dung chuyển khoản đặt cọc.', max_length=20, unique=True, verbose_name='Mã đơn')),
                ('student_name', models.CharField(max_length=200, verbose_name='Họ tên học viên')),
                ('student_phone', models.CharField(db_index=True, max_length=15, verbose_name='SĐT học viên')),
                ('student_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email học viên')),
                ('vehicle_class', models.CharField(choices=[('A1', 'A1 - Mô tô phổ thông dưới 175cc'), ('A', 'A - Mô tô phân khối lớn trên 175cc'), ('B1', 'B1 - Mô tô 3 bánh, xe điện công suất lớn'), ('B_AT', 'B số tự động - Ô tô con dưới 9 chỗ, số tự động'), ('B_MT', 'B số sàn - Ô tô con dưới 9 chỗ'), ('C1', 'C1 - Xe tải dưới 7,5 tấn'), ('C', 'C - Xe tải trên 7,5 tấn'), ('D1', 'D1 - Xe khách đến 16 chỗ'), ('D2', 'D2 - Xe khách trên 16 chỗ')], help_text='Snapshot từ course tại thời điểm convert.', max_length=10, verbose_name='Hạng GPLX')),
                ('tuition_fee', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Học phí')),
                ('deposit_amount', models.DecimalField(decimal_places=0, help_text='Số tiền cọc tối thiểu để giữ chỗ.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cọc cần đóng')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Tổng cộng các Payment đã confirm. Cập nhật từ webhook Casso.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đã đóng')),
                ('status', models.CharField(choices=[('pending', 'Chờ cọc'), ('deposited', 'Đã cọc'), ('partial', 'Đã đóng một phần'), ('completed', 'Đã đóng đủ'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú nội bộ')),
                ('deposit_link_token', models.UUIDField(editable=False, help_text='Token random để chia sẻ link đặt cọc cho HV qua Zalo ZNS.', unique=True, verbose_name='Token trang đặt cọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Đóng cọc lúc')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Đóng đủ lúc')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course', verbose_name='Khóa học')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo đơn')),
                ('lead', models.OneToOneField(blank=True, help_text='OneToOne — mỗi lead chuyển thành tối đa 1 enrollment để đảm bảo idempotent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='leads.lead', verbose_name='Lead gốc')),
            ],
            options={
                'verbose_name': 'Đơn ghi danh',
                'verbose_name_plural': 'Đơn ghi danh',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='orders_enro_status_99e183_idx'), models.Index(fields=['student_phone'], name='orders_enro_student_f9d6ed_idx'), models.Index(fields=['course', 'status'], name='orders_enro_course__52a2cf_idx')],
            },
        ),
    ]
