# Generated by Django 5.0.10 on 2026-06-10 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Phần URL trên FE public: /khoa-hoc/{slug}. Ví dụ: b-so-san.', max_length=200, unique=True, verbose_name='Slug SEO')),
                ('title', models.CharField(max_length=200, verbose_name='Tên khóa')),
                ('vehicle_class', models.CharField(choices=[('A1', 'A1 - Mô tô phổ thông dưới 175cc'), ('A', 'A - Mô tô phân khối lớn trên 175cc'), ('B1', 'B1 - Mô tô 3 bánh, xe điện công suất lớn'), ('B_AT', 'B số tự động - Ô tô con dưới 9 chỗ, số tự động'), ('B_MT', 'B số sàn - Ô tô con dưới 9 chỗ'), ('C1', 'C1 - Xe tải dưới 7,5 tấn'), ('C', 'C - Xe tải trên 7,5 tấn'), ('D1', 'D1 - Xe khách đến 16 chỗ'), ('D2', 'D2 - Xe khách trên 16 chỗ')], max_length=10, verbose_name='Hạng GPLX')),
                ('vehicle_group', models.CharField(choices=[('motorcycle', 'Mô tô'), ('car', 'Ô tô con'), ('truck', 'Xe tải'), ('bus', 'Xe khách'), ('upgrade', 'Nâng hạng')], help_text="Tự động điền theo hạng. Đổi sang 'Nâng hạng' nếu là khóa nâng.", max_length=20, verbose_name='Nhóm')),
                ('short_description', models.CharField(blank=True, help_text='1 câu, hiển thị trên card khóa học.', max_length=255, verbose_name='Mô tả ngắn')),
                ('description_md', models.TextField(blank=True, help_text='Hỗ trợ Markdown. Render trên trang chi tiết khóa.', verbose_name='Mô tả chi tiết (Markdown)')),
                ('tuition_fee', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Học phí')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=200000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đặt cọc giữ chỗ')),
                ('duration_days', models.PositiveIntegerField(default=120, help_text='Số ngày từ khai giảng đến thi sát hạch.', verbose_name='Thời gian (ngày)')),
                ('duration_display', models.CharField(blank=True, help_text="Hiển thị FE. Ví dụ: '4 tháng', '2 tuần'.", max_length=50, verbose_name='Thời gian hiển thị')),
                ('total_slots', models.PositiveIntegerField(default=30, verbose_name='Tổng số suất')),
                ('available_slots', models.PositiveIntegerField(default=30, help_text='Trừ tự động khi convert lead → order.', verbose_name='Còn lại')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Ảnh đại diện')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=170, verbose_name='Meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='OG image')),
                ('is_visible', models.BooleanField(default=True, help_text='Tắt khi ngừng tuyển sinh khóa này. Đơn cũ vẫn xem được trong CRM.', verbose_name='Hiển thị trên FE')),
                ('is_featured', models.BooleanField(default=False, help_text="Card sẽ có badge 'Phổ biến' và viền nổi bật trên FE.", verbose_name='Nổi bật')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_visible', 'sort_order'], name='courses_cou_is_visi_f3c14d_idx'), models.Index(fields=['vehicle_group', 'vehicle_class'], name='courses_cou_vehicle_134712_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày khai giảng')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến thi')),
                ('instructor_name', models.CharField(blank=True, max_length=100, verbose_name='Huấn luyện viên chính')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Sĩ số tối đa')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='Đã đăng ký')),
                ('is_open', models.BooleanField(default=True, help_text='Tắt khi đã đầy slot hoặc đến giờ chốt.', verbose_name='Đang mở')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Lịch khai giảng',
                'verbose_name_plural': 'Lịch khai giảng',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['course', 'is_open', 'start_date'], name='courses_cou_course__2553e4_idx')],
            },
        ),
    ]
