# Generated by Django 5.0.10 on 2026-06-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
