# Generated by Django 5.0.10 on 2026-06-10 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='Khu vực')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ')),
                ('notes', models.TextField(blank=True, default='', help_text='Nội dung khách nhập trong form (yêu cầu, câu hỏi).', verbose_name='Ghi chú từ khách')),
                ('vehicle_class', models.CharField(blank=True, choices=[('A1', 'A1 - Mô tô phổ thông dưới 175cc'), ('A', 'A - Mô tô phân khối lớn trên 175cc'), ('B1', 'B1 - Mô tô 3 bánh, xe điện công suất lớn'), ('B_AT', 'B số tự động - Ô tô con dưới 9 chỗ, số tự động'), ('B_MT', 'B số sàn - Ô tô con dưới 9 chỗ'), ('C1', 'C1 - Xe tải dưới 7,5 tấn'), ('C', 'C - Xe tải trên 7,5 tấn'), ('D1', 'D1 - Xe khách đến 16 chỗ'), ('D2', 'D2 - Xe khách trên 16 chỗ')], default='', max_length=10, verbose_name='Hạng xe quan tâm')),
                ('status', models.CharField(choices=[('new', 'Chưa liên hệ'), ('following', 'Đang theo dõi'), ('success', 'Thành công'), ('failed', 'Thất bại')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(blank=True, choices=[('hot', 'Nóng'), ('warm', 'Ấm'), ('cold', 'Lạnh')], default='', help_text='Set khi status=following.', max_length=10, verbose_name='Độ nóng')),
                ('reason_text', models.CharField(blank=True, default='', help_text='Nếu lý do không có sẵn trong dropdown.', max_length=255, verbose_name='Lý do (text khác)')),
                ('contact_count', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần liên hệ')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần liên hệ gần nhất')),
                ('next_contact_date', models.DateField(blank=True, help_text='Hệ thống nhắc khi tới ngày.', null=True, verbose_name='Hẹn liên hệ tiếp')),
                ('source', models.CharField(choices=[('website', 'Website / form đăng ký'), ('landing', 'Landing page chiến dịch'), ('hotline', 'Gọi hotline'), ('zalo', 'Zalo OA'), ('fb_ads', 'Facebook Lead Ads'), ('phone', 'Gọi điện trực tiếp'), ('referral', 'Giới thiệu'), ('import', 'Import Excel'), ('other', 'Khác')], default='website', max_length=20, verbose_name='Nguồn')),
                ('source_page', models.CharField(blank=True, default='', help_text='URL trang khách submit từ. Ví dụ: /khoa-hoc/b-so-san', max_length=255, verbose_name='Trang nguồn')),
                ('source_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Tiêu đề trang nguồn')),
                ('utm_source', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM content')),
                ('utm_term', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM term')),
                ('device_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Loại thiết bị')),
                ('device_os', models.CharField(blank=True, default='', max_length=50, verbose_name='Hệ điều hành')),
                ('device_browser', models.CharField(blank=True, default='', max_length=50, verbose_name='Trình duyệt')),
                ('screen_size', models.CharField(blank=True, default='', max_length=20, verbose_name='Kích thước màn hình')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User agent')),
                ('converted_to_order', models.BooleanField(default=False, verbose_name='Đã chuyển thành đơn')),
                ('order_code', models.CharField(blank=True, default='', help_text='Liên kết với Enrollment.code sau khi convert. Sẽ chuyển thành FK ở Sprint 1 Tuần 3.', max_length=30, verbose_name='Mã đơn')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Chuyển lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('last_contact_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_contact_leads', to=settings.AUTH_USER_MODEL, verbose_name='Người liên hệ cuối')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead (khách quan tâm)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='leads.lead', verbose_name='Lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Ghi chú nội bộ',
                'verbose_name_plural': 'Ghi chú nội bộ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Lý do')),
                ('status_scope', models.CharField(choices=[('following', 'Đang theo dõi'), ('failed', 'Thất bại')], max_length=20, verbose_name='Áp dụng cho trạng thái')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
            ],
            options={
                'verbose_name': 'Lý do (lead)',
                'verbose_name_plural': 'Danh sách lý do (lead)',
                'ordering': ['status_scope', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['status_scope', 'is_active', 'sort_order'], name='leads_leadr_status__a9cba3_idx')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadreason', verbose_name='Lý do hiện tại'),
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('call', 'Gọi điện'), ('zalo', 'Zalo'), ('sms', 'SMS'), ('email', 'Email'), ('other', 'Khác')], default='call', max_length=20, verbose_name='Hình thức')),
                ('status_before', models.CharField(choices=[('new', 'Chưa liên hệ'), ('following', 'Đang theo dõi'), ('success', 'Thành công'), ('failed', 'Thất bại')], max_length=20, verbose_name='Trạng thái cũ')),
                ('status_after', models.CharField(choices=[('new', 'Chưa liên hệ'), ('following', 'Đang theo dõi'), ('success', 'Thành công'), ('failed', 'Thất bại')], max_length=20, verbose_name='Trạng thái mới')),
                ('priority_after', models.CharField(blank=True, choices=[('hot', 'Nóng'), ('warm', 'Ấm'), ('cold', 'Lạnh')], default='', max_length=10, verbose_name='Độ nóng (sau khi cập nhật)')),
                ('reason_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Lý do (text khác)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú nhân viên')),
                ('next_contact_date', models.DateField(blank=True, null=True, verbose_name='Hẹn liên hệ tiếp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='leads.lead', verbose_name='Lead')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên thực hiện')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='leads.leadreason', verbose_name='Lý do')),
            ],
            options={
                'verbose_name': 'Lần liên hệ',
                'verbose_name_plural': 'Lịch sử liên hệ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='leads_leadc_lead_id_46547e_idx'), models.Index(fields=['user', '-created_at'], name='leads_leadc_user_id_e34404_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='leads_lead_assigne_92225c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_lead_phone_709d42_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_contact_date'], name='leads_lead_next_co_cf1cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', '-created_at'], name='leads_lead_source_ba872b_idx'),
        ),
    ]
