# Generated by Django 5.0.10 on 2026-06-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Định danh hệ thống. VD: cccd_front, portrait, health_cert.', unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hiển thị')),
                ('scope', models.CharField(choices=[('person', 'Gắn với người học'), ('enrollment', 'Gắn với đơn ghi danh')], default='person', max_length=20, verbose_name='Phạm vi')),
                ('is_required', models.BooleanField(default=True, help_text="Nếu bật, FE sẽ liệt kê là 'thiếu' khi HV chưa upload.", verbose_name='Bắt buộc')),
                ('description', models.CharField(blank=True, default='', help_text='Hiển thị cho HV khi chuẩn bị upload.', max_length=500, verbose_name='Hướng dẫn')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Loại tài liệu',
                'verbose_name_plural': 'Loại tài liệu',
                'ordering': ['scope', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Tối đa 5MB. JPG/PNG/WEBP/PDF.', max_length=500, upload_to='documents/%Y/%m/', verbose_name='Tập tin')),
                ('mime_type', models.CharField(blank=True, default='', max_length=50, verbose_name='MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('expired', 'Hết hạn (cần upload lại)'), ('purged', 'Đã xóa theo NĐ 13/2023')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('review_note', models.CharField(blank=True, default='', help_text='Lý do từ chối / hướng dẫn upload lại.', max_length=500, verbose_name='Ghi chú duyệt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc')),
                ('expires_at', models.DateTimeField(blank=True, help_text='CCCD/khám SK xóa sau 90 ngày kể từ khi hoàn thành khóa (NĐ 13/2023).', null=True, verbose_name='Lịch xóa tự động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documenttype', verbose_name='Loại')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.enrollment', verbose_name='Đơn ghi danh')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('uploaded_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.studentaccount', verbose_name='HV upload')),
                ('uploaded_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Văn thư upload hộ')),
            ],
            options={
                'verbose_name': 'Tài liệu theo đơn',
                'verbose_name_plural': 'Tài liệu theo đơn',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['enrollment', 'status'], name='documents_e_enrollm_8c079b_idx'), models.Index(fields=['status', '-created_at'], name='documents_e_status_a747c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Tối đa 5MB. JPG/PNG/WEBP/PDF.', max_length=500, upload_to='documents/%Y/%m/', verbose_name='Tập tin')),
                ('mime_type', models.CharField(blank=True, default='', max_length=50, verbose_name='MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('expired', 'Hết hạn (cần upload lại)'), ('purged', 'Đã xóa theo NĐ 13/2023')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('review_note', models.CharField(blank=True, default='', help_text='Lý do từ chối / hướng dẫn upload lại.', max_length=500, verbose_name='Ghi chú duyệt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc')),
                ('expires_at', models.DateTimeField(blank=True, help_text='CCCD/khám SK xóa sau 90 ngày kể từ khi hoàn thành khóa (NĐ 13/2023).', null=True, verbose_name='Lịch xóa tự động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documenttype', verbose_name='Loại')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.person', verbose_name='Người học')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('uploaded_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.studentaccount', verbose_name='HV upload')),
                ('uploaded_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Văn thư upload hộ')),
            ],
            options={
                'verbose_name': 'Tài liệu cá nhân',
                'verbose_name_plural': 'Tài liệu cá nhân',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['person', 'status'], name='documents_p_person__2a3ec5_idx'), models.Index(fields=['status', '-created_at'], name='documents_p_status_284ee5_idx'), models.Index(fields=['expires_at'], name='documents_p_expires_bfe16b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='persondocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('person', 'document_type'), name='uniq_active_person_doc_per_type'),
        ),
    ]
