# Generated by Django 5.0.10 on 2026-06-10 15:44

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='file',
            field=models.FileField(help_text='Tối đa 5MB. JPG/PNG/PDF.', max_length=500, upload_to=apps.documents.models._private_upload_path, verbose_name='Tập tin'),
        ),
        migrations.AlterField(
            model_name='persondocument',
            name='file',
            field=models.FileField(help_text='Tối đa 5MB. JPG/PNG/PDF.', max_length=500, upload_to=apps.documents.models._private_upload_path, verbose_name='Tập tin'),
        ),
    ]
