# Generated by Django 5.0.10 on 2026-06-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Định dạng chuẩn: 0xxxxxxxxx (10 số).', max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('display_name', models.CharField(blank=True, default='', help_text='Hiển thị trên PWA. Lấy từ Person liên kết hoặc nhập tay.', max_length=200, verbose_name='Tên hiển thị')),
                ('is_active', models.BooleanField(default=True, help_text='Tắt để cấm đăng nhập (vd HV vi phạm).', verbose_name='Đang hoạt động')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần đăng nhập gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Tài khoản học viên',
                'verbose_name_plural': 'Tài khoản học viên',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Số điện thoại')),
                ('code_hash', models.CharField(help_text='SHA-256 hex của mã OTP gốc.', max_length=128, verbose_name='Hash mã OTP')),
                ('purpose', models.CharField(choices=[('login', 'Đăng nhập'), ('verify_phone', 'Xác minh SĐT')], default='login', max_length=20, verbose_name='Mục đích')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác thực'), ('verified', 'Đã xác thực'), ('expired', 'Hết hạn'), ('consumed', 'Đã dùng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Khóa sau 5 lần nhập sai.', verbose_name='Số lần thử')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User agent')),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn lúc')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Đã dùng lúc')),
                ('sent_via', models.CharField(blank=True, default='', help_text='Ví dụ: zalo_zns, sms_fallback, mock_dev.', max_length=20, verbose_name='Gửi qua')),
                ('sent_meta', models.JSONField(blank=True, help_text='Payload từ provider (Zalo ZNS response, error code).', null=True, verbose_name='Metadata gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
            ],
            options={
                'verbose_name': 'Yêu cầu OTP',
                'verbose_name_plural': 'Yêu cầu OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='students_ot_phone_70367a_idx'), models.Index(fields=['status', 'expires_at'], name='students_ot_status_b3a2aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('id_number', models.CharField(blank=True, db_index=True, default='', help_text='12 số (CCCD) hoặc 9 số (CMND cũ). Để trống nếu chưa cấp.', max_length=20, verbose_name='Số CCCD/CMND')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='', max_length=10, verbose_name='Giới tính')),
                ('permanent_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Địa chỉ thường trú')),
                ('current_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Địa chỉ hiện tại')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Người học',
                'verbose_name_plural': 'Người học',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['id_number'], name='students_pe_id_numb_b4cd5d_idx'), models.Index(fields=['full_name'], name='students_pe_full_na_5a6848_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountPersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('self', 'Chính chủ'), ('parent', 'Phụ huynh'), ('child', 'Con'), ('spouse', 'Vợ/chồng'), ('other', 'Khác')], default='self', max_length=20, verbose_name='Quan hệ')),
                ('is_primary', models.BooleanField(default=False, help_text='Bật cho chính chủ tài khoản. Mỗi account chỉ có tối đa 1 primary (nhưng có thể đăng ký hộ N người khác).', verbose_name='Bản thân')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='students.person', verbose_name='Người học')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='students.studentaccount', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Liên kết tài khoản - người học',
                'verbose_name_plural': 'Liên kết tài khoản - người học',
            },
        ),
        migrations.AddConstraint(
            model_name='accountpersonlink',
            constraint=models.UniqueConstraint(fields=('account', 'person'), name='uniq_account_person'),
        ),
    ]
