# Generated by Django 5.0.10 on 2026-06-10 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', help_text='HV nhập tự do. KHÔNG bắt buộc theo NĐ 13/2023.', verbose_name='Lý do yêu cầu')),
                ('status', models.CharField(choices=[('received', 'Đã tiếp nhận'), ('in_review', 'Đang xử lý'), ('approved', 'Đã chấp thuận'), ('rejected', 'Từ chối'), ('completed', 'Đã xóa dữ liệu')], default='received', max_length=20, verbose_name='Trạng thái')),
                ('handler_note', models.TextField(blank=True, default='', help_text='Nội bộ — lý do duyệt/từ chối, các bước đã thực hiện.', verbose_name='Ghi chú xử lý')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User agent')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Đã gửi Telegram lúc')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Xử lý xong lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to='students.studentaccount', verbose_name='Tài khoản học viên')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu xóa dữ liệu (NĐ 13/2023)',
                'verbose_name_plural': 'Yêu cầu xóa dữ liệu (NĐ 13/2023)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='students_st_status_524cef_idx'), models.Index(fields=['account', '-created_at'], name='students_st_account_856d80_idx')],
            },
        ),
    ]
