# Generated by Django 5.0.10 on 2026-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_drop_otprequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountpersonlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('account',), name='uniq_primary_link_per_account'),
        ),
    ]
