# Generated by Django 5.0.10 on 2026-06-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBLeadAdsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(db_index=True, help_text='Idempotent key. FB có thể bắn webhook nhiều lần cùng 1 lead.', max_length=64, unique=True, verbose_name='Lead ID (Facebook)')),
                ('form_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Form ID')),
                ('page_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Page ID')),
                ('ad_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Ad ID')),
                ('adgroup_id', models.CharField(blank=True, default='', max_length=64, verbose_name='AdGroup ID')),
                ('campaign_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Campaign ID')),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='FB tạo lúc')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Raw payload')),
                ('field_data', models.JSONField(blank=True, help_text='Dict {field_name: value} sau khi parse từ Graph API.', null=True, verbose_name='Câu trả lời form')),
                ('status', models.CharField(choices=[('received', 'Đã nhận'), ('processed', 'Đã chuyển vào CRM'), ('duplicate', 'Trùng lead đã có'), ('failed', 'Lỗi xử lý')], default='received', max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Lỗi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Xử lý lúc')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Webhook nhận lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('matched_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fb_lead_ads_events', to='leads.lead', verbose_name='Lead trong CRM')),
            ],
            options={
                'verbose_name': 'Lead FB Ads',
                'verbose_name_plural': 'Lead FB Ads',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', '-received_at'], name='marketing_f_status_d63aae_idx'), models.Index(fields=['page_id', '-received_at'], name='marketing_f_page_id_885e43_idx')],
            },
        ),
    ]
