# Generated by Django 5.0.10 on 2026-06-10 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CassoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(db_index=True, help_text='Idempotent key. Webhook re-send với cùng tid → bỏ qua.', max_length=64, unique=True, verbose_name='Mã GD ngân hàng (tid)')),
                ('casso_id', models.CharField(blank=True, default='', help_text='ID nội bộ của Casso, khác với tid của ngân hàng.', max_length=64, verbose_name='Casso ID')),
                ('description', models.TextField(help_text='Raw description từ ngân hàng. Webhook regex tìm ORD-XXXXXX trong này.', verbose_name='Nội dung CK')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Dương = tiền vào, âm = tiền ra. Chỉ quan tâm dương khi match.', max_digits=14, verbose_name='Số tiền')),
                ('bank_brand_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Ngân hàng')),
                ('bank_sub_acc_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Số TK nhận')),
                ('when', models.DateTimeField(blank=True, help_text='Theo timezone Casso gửi, parse sang UTC để lưu.', null=True, verbose_name='Thời điểm GD')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Match lúc')),
                ('matched_code', models.CharField(blank=True, default='', help_text='Mã ORD-XXXXXX trích từ description bằng regex.', max_length=20, verbose_name='Mã đơn match (regex)')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload raw')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Webhook nhận lúc')),
                ('matched_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casso_transactions', to='orders.enrollment', verbose_name='Đơn được match')),
            ],
            options={
                'verbose_name': 'Giao dịch Casso',
                'verbose_name_plural': 'Giao dịch Casso',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền')),
                ('method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt'), ('casso', 'Casso (tự động)'), ('manual', 'Xác nhận thủ công')], default='casso', max_length=20, verbose_name='Hình thức')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn')], default='confirmed', help_text='Casso/cash mặc định confirmed. Manual cần kế toán duyệt.', max_length=20, verbose_name='Trạng thái')),
                ('bank_tx_id', models.CharField(blank=True, default='', help_text='Lặp lại từ Casso tid để dễ tìm. Không unique vì cash/manual không có.', max_length=64, verbose_name='Mã GD ngân hàng')),
                ('reference_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Mã đơn ghi trong nội dung CK')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Xác nhận lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('casso_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='payments.cassotransaction', verbose_name='Giao dịch Casso')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.enrollment', verbose_name='Đơn')),
            ],
            options={
                'verbose_name': 'Khoản thanh toán',
                'verbose_name_plural': 'Khoản thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cassotransaction',
            index=models.Index(fields=['-received_at'], name='payments_ca_receive_6c8326_idx'),
        ),
        migrations.AddIndex(
            model_name='cassotransaction',
            index=models.Index(fields=['matched_enrollment', '-received_at'], name='payments_ca_matched_58cb09_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['enrollment', '-created_at'], name='payments_pa_enrollm_577341_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank_tx_id'], name='payments_pa_bank_tx_02dcba_idx'),
        ),
    ]
