/**
 * Re-export Phosphor icons không prefix `Ph` để code component đọc thoáng.
 * Phosphor v2 export với prefix → import here, alias bỏ prefix, rồi reuse trong app.
 */
export {
  PhHouse as House,
  PhUsersThree as UsersThree,
  PhClipboardText as ClipboardText,
  PhWallet as Wallet,
  PhFolderSimple as FolderSimple,
  PhGraduationCap as GraduationCap,
  PhShieldCheck as ShieldCheck,
  PhBell as Bell,
  PhCaretDown as CaretDown,
  PhSignOut as SignOut,
  PhUserCircle as UserCircle,
  PhList as List,
  PhPhone as Phone,
  PhEnvelopeSimple as EnvelopeSimple,
  PhChatCircle as ChatCircle,
  PhHash as Hash,
  PhClock as Clock,
  PhCheckCircle as CheckCircle,
  PhXCircle as XCircle,
  PhArrowsClockwise as ArrowsClockwise,
  PhX as X,
  PhCaretRight as CaretRight,
  PhTrendUp as TrendUp,
  PhArrowRight as ArrowRight,
  PhArrowLeft as ArrowLeft,
  PhMapPin as MapPin,
  PhCalendar as Calendar,
  PhChatCircleDots as ChatCircleDots,
  PhGlobe as Globe,
  PhTag as Tag,
  PhMagnifyingGlass as MagnifyingGlass,
  PhFunnelSimple as FunnelSimple,
  PhPlus as Plus,
  PhLock as Lock,
  PhUser as User,
  PhEye as Eye,
  PhEyeSlash as EyeSlash,
  PhFilePdf as FilePdf,
  PhFileXls as FileXls,
  PhChartBar as ChartBar,
  PhReceipt as Receipt,
  PhPlugsConnected as PlugsConnected,
  PhKey as Key,
  PhFacebookLogo as FacebookLogo,
  PhBank as Bank,
  PhFloppyDisk as FloppyDisk,
  PhInfo as Info,
  PhCheck as Check,
  PhWarning as Warning,
} from '@phosphor-icons/vue'
